version: '2'
services:
  details:
    image: istio/examples-bookinfo-details-v1:latest
  ratings:
    image: istio/examples-bookinfo-ratings-v1:latest
  reviews:
    image: istio/examples-bookinfo-reviews-v2:latest
  productpage:
    image: istio/examples-bookinfo-productpage-v1:latest
    ports:
    - 80:9080
  opa:
    image: openpolicyagent/opa:0.24.0
    volumes:
    - ./policies:/policies
    command:
    - run
    - --server
    - --watch
    - --log-format=json-pretty
    - --set=decision_logs.console=true
    - /policies
    ports:
    - 8181:8181